### ISSUE TITLE
RFC Adding an anchor attribute for each component.

### ISSUE THREAD

**Issue by nahumzs** [acl-services/paprika#101]
https://github.com/acl-services/paprika/pull/84/files#r296462713

While implementing the SidePanel there was a small discussion about the benefit that would bring to add a data anchor attribute to our components. This would help in targeting them easier in CSS/SCSS/JSS and while testing.

Example:
Let's put a scenario where we want to build a `SuperDupper` component the return "render" would look like:

```js
export default function SuperDupper(props) {
  return (<div {...props} data-display-name="SuperDupper">Super Dupper</div>)
} 
```

so in a consumer app if you need to modify this component by any specific requirement or accessing it by testing could do:

```css
/* css/jss/scss */
[data-display-name="SuperDupper"] { color: red; }
```
___or 

```js
  // testing
  expect(cy.queryBy('[data-component-type="listbox.filter"]')).toBeInTheDocument()
```

Thoughts?

**Comment by mikrotron** [comment]
This can be achieved by adding a `className` to the component, and then using that selector to target instead, but: 

1) When composing Paprika components, adding `classNames` is being avoided in favour of a purely `styled-components` approach. 

2) In an app where, for example, there are a number of buttons you want to apply spacing to for your layout, it's cumbersome to apply a custom className to all of them.  It's more convenient to do:
```scss
.myComponent {
  [data-component-type='button'] { 
    margin-right: 16px; 
  }
}
```
